dist: bionic

language: node_js

node_js: 12

install:
  # Install NodeJS modules (excluding optional modules)
  - npm install --no-optional --no-shrinkwrap --no-package-lock

script: 
  - npm run prestart